print(issubclass(ValueError, Exception))
print(issubclass(TypeError, Exception))
print(issubclass(FileNotFoundError, OSError))
print(issubclass(OSError, Exception))
print(issubclass(Exception, BaseException))